image: gitpod/workspace-mongodb

tasks:
  - name: Opening Swagger UI
    command: gp await-port 8080 && gp preview $(gp url 8080)/swagger-ui.html; exit
  - name: MongoDB # Start MongoDB
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: Project # Start the project in development mode
    init: ./mvnw dependency:resolve && ./mvnw compile # This runs during Gitpod prebuild
    command: ./mvnw spring-boot:run
  - name: Terminal # Opens a blank terminal at the right side

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - redhat.java@0.60.0:Oq41RaXQP8j6cjNglFQqAQ==
    - GabrielBB.vscode-lombok@1.0.1:IAvPOHnFmUYZpRqErUNAiQ==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - vscjava.vscode-spring-boot-dashboard@0.1.8:HcUY2EBWUzLI8LYU/I2Flg==
    - Pivotal.vscode-spring-boot@1.17.0:mGdRFTP1eLVuk7lwGhEWRg==
    - vscjava.vscode-java-dependency@0.9.0:0lYT1u+1Pgn1oAUG5na4cQ==
    - vscjava.vscode-java-debug@0.25.1:yUSBAu6nHsJCoKr2noLqvw==
    - vscjava.vscode-maven@0.21.2:eUANtFfmlMMlJemdLOZs4A==
    - vscjava.vscode-java-test@0.22.3:r0wZhaCeRHUpyUd2S8C/Tw==
