image: gitpod/workspace-mongodb

tasks:
  # - command: sleep 30; gp preview "$(gp url 8080)/swagger-ui.html"; exit
  - name: MongoDB
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: ./mvnw dependency:resolve && ./mvnw compile
    command: ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - GabrielBB.vscode-lombok@1.0.1:IAvPOHnFmUYZpRqErUNAiQ==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - vscjava.vscode-spring-boot-dashboard@0.1.8:HcUY2EBWUzLI8LYU/I2Flg==
    - Pivotal.vscode-spring-boot@1.15.0:8Ly0sETgWlmYi2D3uXi7FA==
    - vscjava.vscode-java-test@0.22.2:ZBznuSuKUJo5X8dZe6b9Nw==
    - vscjava.vscode-maven@0.21.0:37ZOg7jK2M04yXsE+ItbZg==
    - vscjava.vscode-java-dependency@0.9.0:0lYT1u+1Pgn1oAUG5na4cQ==
    - vscjava.vscode-java-debug@0.25.0:kzrHloDvSyL81jltUd00Eg==
    - redhat.java@0.60.0:Oq41RaXQP8j6cjNglFQqAQ==
